/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.2 and the DSP System Toolbox 9.4.
 * Generated on: 30-May-2018 15:42:15
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 40
 * Stable            : Yes
 * Linear Phase      : Yes (Type 2)
 * Arithmetic        : single
 */

/* General type conversion for MATLAB generated C-code  */

/*
 * Expected path to tmwtypes.h
 * C:\Program Files\MATLAB\R2017a\extern\include\tmwtypes.h
 */

float Hlp[CoefSize] = {
  -0.0001058247144,-0.003036818467,-0.007088692393, -0.01214145962, -0.01561728399,
   -0.01465814374,-0.007587981876, 0.004402833525,   0.0167098958,  0.02270098962,
    0.01690693013,-0.001316639944, -0.02563640103, -0.04376792535, -0.04193049669,
   -0.01116868481,  0.04733457416,   0.1207813025,    0.188363567,   0.2288243324,
     0.2288243324,    0.188363567,   0.1207813025,  0.04733457416, -0.01116868481,
   -0.04193049669, -0.04376792535, -0.02563640103,-0.001316639944,  0.01690693013,
    0.02270098962,   0.0167098958, 0.004402833525,-0.007587981876, -0.01465814374,
   -0.01561728399, -0.01214145962,-0.007088692393,-0.003036818467,-0.0001058247144
};
