/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.2 and the Signal Processing Toolbox 7.4.
 * Generated on: 06-Jun-2018 23:22:36
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 40
 * Stable            : Yes
 * Linear Phase      : Yes (Type 2)
 */

/* General type conversion for MATLAB generated C-code  */

/*
 * Expected path to tmwtypes.h
 * C:\Program Files\MATLAB\R2017a\extern\include\tmwtypes.h
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   int16 filter coefficients.
 */
#define DC_gainHp 32767
int Ghp[40] = {
       -3,   -100,   -232,   -398,   -512,   -480,   -249,    144,    548,
      744,    554,    -43,   -840,  -1434,  -1374,   -366,   1551,   3958,
     6172,   7498,   7498,   6172,   3958,   1551,   -366,  -1374,  -1434,
     -840,    -43,    554,    744,    548,    144,   -249,   -480,   -512,
     -398,   -232,   -100,     -3
};
